### PR TITLE
Add `color` Option to Gnuplot; Enhance `build.sh`

### PR DESCRIPTION
**Pull request by AndiH**
* For my Gnuplot version, I needed to add option `color` to the `set term` line. This seems to be generally not a bad thing to add
* `build.sh` now has command line options to produce either PNGs or PDFs from the EPS figures
* Some cleanup and updating (README, gitignore)…

### CODE REVIEW

**Comment by karlrupp** [comment]
Awesome, thank you, Andi!

**Comment by AndiH** [comment]
I'm preparing our 2017 CUDA course :)

**Comment by karlrupp** [comment]
What about OpenCL? ;-)

**Comment by AndiH** [comment]
We'll host an OpenCL course in November (http://www.fz-juelich.de/SharedDocs/Termine/IAS/JSC/DE/Kurse/2017/gpu-opencl-2017.html?nn=2022346); but I'm not involved  in this one. OpenACC and CUDA is enough for me ;).

**Pull request merged**
